### ISSUE TITLE
ValueError: dictionary update sequence element #12 has length 1; 2 is required

### ISSUE THREAD

**Issue by jirislaby** [newren/git-filter-repo#659]
In:
https://github.com/newren/git-filter-repo/commit/fa3af4fafc548ece016fa62555693ae2c679d854#diff-55bd61ae2b93029c1b55e3cb36a0ef2e29463831a4f5343465b0dc12d84ab509R1562

https://github.com/newren/git-filter-repo/blob/2d391462dca14cd18b8faaefce34dc91dc1ae150/git-filter-repo#L1692-L1693

I get the below when running [b4](https://git.kernel.org/pub/scm/utils/b4/b4.git) tests:
```
/home/abuild/rpmbuild/BUILD/b4-0.14.2-build/b4-0.14.2/src/tests/test_ez.py:73: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/abuild/rpmbuild/BUILD/b4-0.14.2-build/b4-0.14.2/src/b4/ez.py:2858: in cmd_trailers
    update_trailers(cmdargs)
/home/abuild/rpmbuild/BUILD/b4-0.14.2-build/b4-0.14.2/src/b4/ez.py:1216: in update_trailers
    frf.run()
/usr/lib/python3.13/site-packages/git_filter_repo.py:4876: in run
    self._run_sanity_checks()
/usr/lib/python3.13/site-packages/git_filter_repo.py:3277: in _run_sanity_checks
    self._config_settings = GitUtils.get_config_settings(target_working_dir)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

repo_working_dir = b'.'

    @staticmethod
    def get_config_settings(repo_working_dir):
      output = ''
      try:
        output = subproc.check_output('git config --list'.split(),
                                      cwd=repo_working_dir)
      except subprocess.CalledProcessError as e: # pragma: no cover
        raise SystemExit('fatal: {}'.format(e))
    
      # FIXME: Ignores multi-valued keys, just let them overwrite for now
>     return dict(line.split(b'=', maxsplit=1)
                  for line in output.strip().split(b"\n"))
E     ValueError: dictionary update sequence element #12 has length 1; 2 is required
```

Because the `git config` output contains empty lines:
```
L=b'core.repositoryformatversion=0'
L=b'core.filemode=true'
L=b'core.bare=false'
L=b'core.logallrefupdates=true'
L=b'remote.origin.url=/home/abuild/rpmbuild/BUILD/b4-0.14.2-build/b4-0.14.2/src/tests/samples/gitdir.bundle'
L=b'remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*'
L=b'branch.master.remote=origin'
L=b'branch.master.merge=refs/heads/master'
L=b'user.name=Test Override'
L=b'user.email=test-override@example.com'
L=b'branch.b4/pytest.b4-prep-cover-strategy=branch-description'
L=b'branch.b4/pytest.description=EDITME: cover title for pytest'
L=b''                                           <--------------------------------------------- this is element #12
L=b'# Describe the purpose of this series. The information you put here'
L=b'# will be used by the project maintainer to make a decision whether'
L=b'# your patches should be reviewed, and in what priority order. Please be'
L=b'# very detailed and link to any relevant discussions or sites that the'
L=b'# maintainer can review to better understand your proposed changes. If you'
L=b'# only have a single patch in your series, the contents of the cover'
L=b'# letter will be appended to the "under-the-cut" portion of the patch.'
L=b''
L=b'# Lines starting with # will be removed from the cover letter. You can'
L=b'# use them to add notes or reminders to yourself. If you want to use'
L=b'# markdown headers in your cover letter, start the line with ">#".'
L=b''
L=b'# You can add trailers to the cover letter. Any email addresses found in'
L=b'# these trailers will be added to the addresses specified/generated'
L=b'# during the b4 send stage. You can also run "b4 prep --auto-to-cc" to'
L=b'# auto-populate the To: and Cc: trailers based on the code being'
L=b'# modified.'
L=b''
L=b'Signed-off-by: Test Override <test-override@example.com>'
L=b''
L=b''
L=b'branch.b4/pytest.b4-tracking={"series": {"revision": 1, "change-id": "20250424-pytest-9dfb9c4f8059", "prefixes": [], "base-branch": "master"}}'
```

**Comment by jirislaby** [comment]
Fixed by 4697eeb37b7c3c30b0492e344f6b89f7139cef26.

**Comment by minahkim-data** [comment]
> [@newren](https://github.com/newren) could you make a new release with this fix included please? `b4` uses `git-filter-repo`, and it's impossible to use without this if the `git config --list` output has empty lines.

This comment was very helpful. I figured out that there was a '\n' at the end of my user email (as a global configuration), and fixing this solved my issue when using `git filter-repo --path /path/ --invert-paths` My error message was `ValueError: dictionary update sequence element #14 has length 1; 2 is required`

**Comment by paulirish** [comment]
Hit this too. It happens if the user's git config contains multi-line aliases, comments, or keys without values. Mine was cuz of a trailing `#` in a git alias. 

Echoing https://github.com/newren/git-filter-repo/issues/659#issuecomment-2890567018 this is still not yet in a release.  

Applying https://github.com/newren/git-filter-repo/commit/4697eeb37b7c3c30b0492e344f6b89f7139cef26 locally will do the trick, of course.

**Comment by Joebeazelman** [comment]
I'm encountering the same exact error on MacOS 27. It doesn't appear to have been fixed at least on version 2.47.0

**Comment by serpro69** [comment]
If you don't want to look for misbehaving config value, here's a workaround to disable custom configs:

```bash
GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_NOGLOBAL=1 GIT_CONFIG=.git/config git filter-repo ...
```

Maybe this will be useful for someone who stumbles upon this issue.

**Comment by Joebeazelman** [comment]
Thanks, but I couldn't see anything wrong with my file. I got around it by clearing out the configuration file. It's an OK solution, since it removes the origin from the configuration after splitting a repo anyway, plus it's not something I would run regularly, I'm fine with this workaround.
